import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Navbar from "@/Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export default function register() {
  const [name, setName] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");

  const submitForm = async (e) => {
    e.preventDefault();
    const data = {
      Name: name,
      Email: email,
      Password: password,
      Pokemons: [],
    };
    const response = await fetch("https://poke-crypto.vercel.app/api/Register", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(data),
    });
    const result = await response.json();
    console.log(result);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
        <Navbar/>
          <div className="container mt-5">
            <h2>Register</h2>
            <form className="d-flex flex-column justify-content-center align-items-center" onSubmit={submitForm}>
              <div className="form-group mb-5">
                <label htmlFor="name">Name</label>
                <input type="text" className="form-control" id="name" placeholder="Enter name" value={name} onChange={(e) => setName(e.target.value)} />
              </div>
              <div className="form-group mb-5">
                <label htmlFor="email">Email address</label>
                <input type="email" className="form-control" id="email" placeholder="Enter email" value={email} onChange={(e) => setEmail(e.target.value)} />
              </div>
              <div className="form-group mb-5">
                <label htmlFor="password">Password</label>
                <input type="password" className="form-control" id="password" placeholder="Password" value={password} onChange={(e) => setPassword(e.target.value)} />
              </div>
              <button type="submit" className="btn btn-primary mb-5">
                Register
              </button>
            </form>
          </div>
          <footer className="text-center py-4">
            <p>© 2024 PokeCrypto. All rights reserved.</p>
          </footer>
        </div>
      </main>
    </>
  );
}
